spring:
  data:
    mongodb:
      # retryWrites = Desabilita as re-tentativas de escrita no cluster
      uri: mongodb://localhost:27040/blog?retryWrites=false
#      uri: mongodb://localhost:27017/blog
#      username:
#      password: